services:
  python_api:
    env_file:
      - .env
    build:
      context: ./docker/python
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
    volumes:
      - ./app:/srv/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mariadb_api

  mariadb_api:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - mariadb_volume_api:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  python_volume_api:
  mariadb_volume_api:
